[options]

db_host = localhost
db_port = 5432
db_user = odoo
db_password = admin
admin_passwd = admin
# dbfilter = Alibaba-DB-pro-main-test-1
# dbfilter = ^%d$
http_port = 8018
# http_interface = 
addons_path = D:\odoo\odoo18\addons,D:\odoo\custom_addons\project-18\custom-addons
# load_translations = False
# dbfilter = ^%d$

limit_time_cpu = 10000
limit_time_real = 5000
limit_memory_hard = 3684354560
limit_memory_soft = 3147483648

# sudo nano /etc/systemd/system/odoo.service


# [Unit]
# Description=Odoo
# Documentation=http://www.odoo.com
# After=network.target

# [Service]
# Type=simple
# SyslogIdentifier=odoo
# PermissionsStartOnly=true
# User=root
# ExecStart=/root/.pyenv/versions/3.11.3/bin/python3 /root/odoo/odoo-bin -c /etc/odoo.conf
# StandardOutput=journal+console

# [Install]
# WantedBy=multi-user.target


# sudo systemctl restart odoo.service
# sudo systemctl status odoo.service


# sudo cp /root/odoo/debian/odoo.conf /etc/odoo.conf
# sudo nano /etc/odoo.conf



